project_name: "LightSplat_ROS"
dataset_name: "realsense"
checkpoint_path: null
use_wandb: False
frame_limit: -1 # for debugging, set to -1 to disable
seed: 0
mapping:
  new_submap_every: 50
  map_every: 1
  iterations: 40
  new_submap_iterations: 100
  new_submap_points_num: 100000 
  new_submap_gradient_points_num: 50000 
  new_frame_sample_size: 30000 
  new_points_radius: 0.0001
  current_view_opt_iterations: 0.4 # What portion of iterations to spend on the current view
  alpha_thre: 0.6
  pruning_thre: 0.5
  submap_using_motion_heuristic: True
tracking:
  gt_camera: False
  w_color_loss: 0.6
  iterations: 200
  cam_rot_lr: 0.002
  cam_trans_lr: 0.01
  odometry_type: "const_speed"  # gt, const_speed, odometer
  help_camera_initialization: False # temp option to help const_init
  init_err_ratio: 5
  odometer_method: "hybrid" # hybrid or point_to_plane
  filter_alpha: False
  filter_outlier_depth: False
  alpha_thre: 0.98
  soft_alpha: True
  mask_invalid_depth: True
  enable_exposure: False
cam:
  H: 480
  W: 640
  fx: 388.49907
  fy: 388.37614
  cx: 319.91859
  cy: 244.78187
  # H: 240
  # W: 424
  # fx: 214.830521
  # fy: 214.810836
  # cx: 211.982044
  # cy: 122.540309
  crop_edge: 0
  distortion: [0, 0, 0, 0, 0]
  depth_scale: 1000.0
lc:
  min_similarity: 0.5
  pgo_edge_prune_thres: 0.25
  voxel_size: 0.1
  pgo_max_iterations: 500
  registration:
    method: "gs_reg"
    base_lr: 5.e-3
    min_overlap_ratio: 0.2
    use_render: False
  min_interval: 3
  final: False
data:
  input_path: scripts/output/RealSense/data/
  output_path: scripts/output/RealSense/run/
  scene_name: realsense
ros:
  frames_topic: /frames
  ros_virtual_length: 3000 # simulated dataset length
light:
  used: True
  max_num_keypoints: 1000
  max_thresh_dist: 0.5
  max_thresh_angle: 15.0
  relocalize_max_thresh_dist: 1.0
  relocalize_max_thresh_angle: 60.0
  min_keyframe_dist: 0.08
  min_keyframe_angle: 10.0
  sliding_window: 10
  registration_mode: "fast"  # fast, normal
